# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeautomation', '0012_auto_20150926_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
