# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeautomation', '0014_auto_20171128_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedatapoint',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
